name: 'Update Development'

on:
  push:
    branches:
      - staging

jobs:
  nightly-merge:
    name: Update Development
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.3.1
      with:
        stable_branch: 'staging'
        development_branch: 'development'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
